/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as PayRouteImport } from './routes/pay'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories.$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/loans': typeof LoansRoute
  '/pay': typeof PayRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/accounts/': typeof AccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/loans': typeof LoansRoute
  '/pay': typeof PayRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/accounts': typeof AccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/loans': typeof LoansRoute
  '/pay': typeof PayRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/accounts/': typeof AccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/goals'
    | '/history'
    | '/loans'
    | '/pay'
    | '/reports'
    | '/settings'
    | '/accounts/$accountId'
    | '/categories/$categoryId'
    | '/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/goals'
    | '/history'
    | '/loans'
    | '/pay'
    | '/reports'
    | '/settings'
    | '/accounts/$accountId'
    | '/categories/$categoryId'
    | '/accounts'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/goals'
    | '/history'
    | '/loans'
    | '/pay'
    | '/reports'
    | '/settings'
    | '/accounts/$accountId'
    | '/categories/$categoryId'
    | '/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRoute
  GoalsRoute: typeof GoalsRoute
  HistoryRoute: typeof HistoryRoute
  LoansRoute: typeof LoansRoute
  PayRoute: typeof PayRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRoute,
  GoalsRoute: GoalsRoute,
  HistoryRoute: HistoryRoute,
  LoansRoute: LoansRoute,
  PayRoute: PayRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
